# Generated by Django 2.0.1 on 2018-02-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1000)),
                ('edu', models.CharField(max_length=1000)),
                ('expertise', models.CharField(max_length=1000)),
                ('religion', models.CharField(max_length=1000)),
                ('race', models.CharField(max_length=1000)),
                ('marriage', models.CharField(max_length=1000)),
                ('grow_city', models.CharField(max_length=1000)),
                ('grow_town', models.CharField(max_length=1000)),
                ('fill_city', models.CharField(max_length=1000)),
                ('fill_town', models.CharField(max_length=1000)),
                ('whatIsWisdom', models.CharField(max_length=1000)),
                ('is_wisdom1', models.IntegerField()),
                ('most_wisdom', models.CharField(max_length=1000)),
                ('most_wisdom_year', models.IntegerField()),
                ('most_wisdom_old', models.IntegerField()),
                ('most_wisdom_period', models.IntegerField()),
                ('special', models.CharField(max_length=1000)),
                ('wisdom_perform', models.IntegerField()),
                ('think', models.CharField(max_length=1000)),
                ('idea', models.IntegerField()),
                ('postiveEffect', models.IntegerField()),
                ('who_postiveEffect', models.IntegerField()),
                ('what_postiveEffect', models.IntegerField()),
                ('think_period', models.IntegerField()),
                ('is_wisdom2', models.IntegerField()),
                ('why_wisdom', models.CharField(max_length=1000)),
                ('realize', models.IntegerField()),
                ('why_realize', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='which',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Rating'),
        ),
    ]
