# Generated by Django 2.0.1 on 2018-02-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20180202_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='fill_time',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
